USE soc_radar;

ALTER TABLE security_events
MODIFY COLUMN event_type ENUM(
  'SSH_FAILED',
  'SSH_SUCCESS',
  'SFTP_FAILED',
  'SFTP_SUCCESS',
  'FTP_FAILED',
  'FTP_SUCCESS',
  'XRDP_FAILED',
  'XRDP_SUCCESS',
  'FAIL2BAN_BLOCK',
  'FAIL2BAN_UNBLOCK',
  'UNKNOWN'
) NOT NULL DEFAULT 'UNKNOWN';
